### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by HerozuKa** [rlzicar/Chessticle#2] opened 2023-09-24 15:37 UTC
On the first launch when trying to connect, a connection error pops up. When we then select find a new opponent everything connects perfectly. Where to look for the error?

**Comment by rlzicar** [comment] 2023-09-25 07:03
Thanks for bringing this to my attention. It seems like it was caused by certain changes in the latest version of PUN. It should be fixed now.

**Comment by HerozuKa** [comment] 2023-09-25 07:06
> Thanks for bringing this to my attention. It seems like it was caused by certain changes in the latest version of PUN. It should be fixed now.

A piece of great work. Sincere greetings and gratitude for your quick response and help. Greetings

**Closed as completed** 2023-09-25 07:12 UTC
