### ISSUE TITLE
Photon Update

### ISSUE THREAD

**Issue by DevSpur** [rlzicar/Chessticle#3] opened 2024-11-01 11:50 UTC
Hi there I was using your asset and it was working great then all of a sudden it stopped working, I don't know if you will be able to help.

I think it's got something to do with the photon update. 

So what's happening is everything connects as normal, when the white player moves it updates normally and I can see that it is receiving the RPC call, Then the game moves to the black player and then nothing happens the timer doesn't even count down and you cannot move any pieces.

**Comment by rlzicar** [comment] 2024-11-04 09:35
Hi, thanks for bringing this to my attention. It was indeed caused by some changes in the recent versions of Photon. This issue is fixed by commit 4ecbd16ac473d82a3c78240d4e0b05e7e2f8a308

**Closed as completed** 2024-11-04 09:37 UTC
